config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :songs
	root :to => "songs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
	validates_presence_of :name,:link,:user
	validates_format_of :link, :with => URI::regexp(%w(http https))
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	before_action :set_song, :only => [ :show, :edit, :update, :destroy ]
	def index
		if params[:id]
			@song = Song.find(params[:id])
		else
			@song = Song.new
		end
		@songs = Song.page(params[:page]).per(5)
		
	end

	def create
		@song = Song.new(song_params)
		if @song.save
			flash[:notice] = "新增成功"
			redirect_to  songs_path(:page=>params[:page])
		else
			@songs = Song.page(params[:page]).per(5)
			flash[:alert] = "新增失敗"
			render :action => :index
		end
	end

	def update
		if @song.update(song_params)
			flash[:notice] = "修改成功"
			redirect_to  songs_path(:page=>params[:page])
		else
			@songs = Song.page(params[:page]).per(5)
			flash[:alert] = "修改失敗"
			render :action => :index
		end
	end
	
	def destroy
		@song.destroy
		flash[:notice] = "刪除成功"
		redirect_to songs_path(:page=>params[:page])
	end
		
	private

	def set_song
		@song = Song.find(params[:id])
	end

	def song_params
		params.require(:song).permit(:name,:link,:user)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YouTube</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
	  <div class="container">
	  	<div class="row">
	  		<div class="col-md-12 col-sm-12 col-xs-12">
	  			<% if flash[:notice].present? %>
		  			<div class="alert alert-success" role="alert">
			  			<p style="color:black"><%= flash[:notice] %></p>
			  		</div>
		  		<% end %>
	  			<% if flash[:alert].present? %>
			  		<div class="alert alert-danger" role="alert">
			  			<p style="color:black"><%= flash[:alert] %></p>
		  			</div>
	  			<% end %>
			  	<%= yield %>	  			
	  		</div>
	  	</div>
	  </div>
  </body>
</html>

app/views/songs/_newform.html.erb
<table class="table table-hover table-bordered">
<tr>
	<td width="15%"><%= s.text_field :name ,:class=>"form-control",:placeholder=>"Song Name"%></td>
	<td><%= s.text_field :link,:class=>"form-control" ,:placeholder=>"YouTube Link"%></td>
	<td width="20%"><%= s.text_field :user,:class=>"form-control" ,:placeholder=>"
User Name"%></td>
	<td width="5%">
		<%= link_to "", songs_path(:page=>params[:page]), :class=>"btn btn-default glyphicon glyphicon-remove" %>
	</td>
	<td width="5%">
		<%= s.submit "＋",:class=>"btn btn-success" %>
	</td>
	
</tr>
</table>

app/views/songs/index.html.erb
<h3>YouTube Playlist</h3>
<% if @song.id %>
	<%= form_for @song, :url => song_path(@song,:page=>params[:page]),:method =>:patch do |s|%>			
		<%= render :partial => "newform",:locals => { :s =>s } %>
	<% end %>
<% else %>
	<%= form_for @song, :url => songs_path(:page=>params[:page])do |s|%>			
		<%= render :partial => "newform",:locals => { :s =>s } %>
	<% end %>
<% end %>

<table class="table table-hover table-bordered">
	<tr>
		<th width="15%">Song</th>
		<th>YouTube Link</th>
		<th width="15%">Uploaded By</th>
		<th width="5%">Info</th>
		<th width="5%">Edit</th>
		<th width="5%">Dele</th>
	</tr>
	<% @songs.each do |s| %>
	<tr>
		<td><%= s.name %></td>
		<td><%= s.link %></td>
		<td><%= s.user %></td>
		<td><%= link_to "",song_path(s,:page => params[:page]),:class=>"btn btn-info glyphicon glyphicon-search"%></td>
		<td><%= link_to "",songs_path(:page => params[:page], :id => s.id),:class=>"btn btn-default glyphicon glyphicon-pencil"%></td>
		<td><%= link_to "",song_path(s,:page => params[:page]),:method=>:delete,:data=>{:confirm=>"Are you sure?"},:class=>"btn btn-danger glyphicon glyphicon-trash"%></td>
	</tr>
	<% end %>

</table>

<%= Time.now.asctime %>
<%= paginate @songs , :window => 1 %>

app/views/songs/show.html.erb
<p></p>
<div class="panel panel-default">
	<div class="panel-heading"><%= @song.name %></div>
	<table class="table table-bordered">
		<tr>
			<th>Link</th>
			<td><%= @song.link %></td>
		</tr>
		<tr>
			<th>User</th>
			<td><%= @song.user %></td>
		</tr>
	</table>
</div>
<%= link_to "Back",songs_path(:page=>params[:page]),:class=>"btn btn-default pull-right" %>